M48
; DRILL file {KiCad 7.0.9-7.0.9~ubuntu22.04.1} date mié 20 dic 2023 17:41:01
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-12-20T17:41:01-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9-7.0.9~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X63.0Y-48.0
X64.0Y-100.5
X131.0Y-47.75
X131.0Y-80.25
T0
M30
